# ==============================================================================
# Bare-Metal AMP TMR Flight Computer - Automated QEMU Regression Test Runner
# ==============================================================================

$qemu = "D:\tools\qemu\qemu-system-arm.exe"
if (-not (Test-Path $qemu)) {
    $qemu = "qemu-system-arm.exe"
}

$outputFile = "qemu_flight_test_log.txt"
if (Test-Path $outputFile) { Remove-Item $outputFile -Force }

$qemuArgs = "-M vexpress-a15 -cpu cortex-a15 -smp 4 -nographic -kernel tmr_flight_computer.elf -accel tcg,thread=multi"

Write-Host "[INFO] Starting QEMU flight computer simulation..." -ForegroundColor Cyan
$proc = Start-Process -FilePath $qemu -ArgumentList $qemuArgs -NoNewWindow -RedirectStandardOutput $outputFile -PassThru

# Allow 4 seconds for full automated suite and continuous loop to execute
Start-Sleep -Seconds 4

if (-not $proc.HasExited) {
    Stop-Process -Id $proc.Id -Force
}
Start-Sleep -Milliseconds 200

if (Test-Path $outputFile) {
    Write-Host "==============================================================================" -ForegroundColor Green
    Write-Host "                QEMU SIMULATION OUTPUT CAPTURE" -ForegroundColor Green
    Write-Host "==============================================================================" -ForegroundColor Green
    Get-Content $outputFile
    Remove-Item $outputFile -Force
} else {
    Write-Host "[ERROR] Output log file was not generated by QEMU." -ForegroundColor Red
    exit 1
}
